# nginx image
FROM nginx:1.20-alpine

RUN apk update && apk upgrade --no-cache

COPY index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf.d/default.conf


RUN chown -R nginx:nginx /usr/share/nginx/html

USER nginx