name: Apply

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "landing-zone/azure/dev/**"
      - "landing-zone/azure/prod/**"
      - "modules/**"

permissions:
  contents: read
  id-token: write

concurrency:
  group: terragrunt-apply-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  infra-azure-dev-plan:
    uses: ./.github/workflows/tg-plan.yaml
    with:
      stack: azure
      environment: dev
    secrets: inherit

  infra-azure-prod-plan:
    uses: ./.github/workflows/tg-plan.yaml
    with:
      stack: azure
      environment: prod
    secrets: inherit

  review-dev:
    needs: infra-azure-dev-plan
    if: needs.infra-azure-dev-plan.result == 'success'
    runs-on: ubuntu-latest
    environment: dev-review

    steps:
      - name: Approval completed
        run: echo "Approved"

  review-prod:
    needs: infra-azure-prod-plan
    if: needs.infra-azure-prod-plan.result == 'success'
    runs-on: ubuntu-latest
    environment: prod-review

    steps:
      - name: Approval completed
        run: echo "Approved"

  infra-azure-dev-apply:
    needs:
      - infra-azure-dev-plan
      - review-dev
    if: needs.review-dev.result == 'success'
    uses: ./.github/workflows/tg-apply.yaml
    with:
      stack: azure
      environment: dev
    secrets: inherit

  infra-azure-prod-apply:
    needs:
      - infra-azure-prod-plan
      - review-prod
    if: needs.review-prod.result == 'success'
    uses: ./.github/workflows/tg-apply.yaml
    with:
      stack: azure
      environment: prod
    secrets: inherit
