name: Apply

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "landing-zone/azure/dev/**"
      - "landing-zone/azure/prod/**"
      - "modules/**"

permissions:
  contents: read
  id-token: write

concurrency:
  group: terragrunt-apply-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  infra-azure-dev-plan:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/tg-plan.yaml
    with:
      stack: azure
      environment: dev
    secrets: inherit

  infra-azure-prod-plan:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/tg-plan.yaml
    with:
      stack: azure
      environment: prod
    secrets: inherit

  review:
    needs:
      - infra-azure-dev-plan
      - infra-azure-prod-plan
    if: |
      always() &&
      needs.infra-azure-dev-plan.result != 'failure' && needs.infra-azure-dev-plan.result != 'cancelled' &&
      needs.infra-azure-prod-plan.result != 'failure' && needs.infra-azure-prod-plan.result != 'cancelled'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod-review' || 'dev-review' }}

    steps:
      - name: Approval completed
        run: echo "Approved"

  infra-azure-dev-apply:
    needs:
      - infra-azure-dev-plan
      - review
    if: github.ref_name == 'dev' && needs.review.result == 'success'
    uses: ./.github/workflows/tg-apply.yaml
    with:
      stack: azure
      environment: dev
    secrets: inherit

  infra-azure-prod-apply:
    needs:
      - infra-azure-prod-plan
      - review
    if: github.ref_name == 'main' && needs.review.result == 'success'
    uses: ./.github/workflows/tg-apply.yaml
    with:
      stack: azure
      environment: prod
    secrets: inherit
